# Generated by Django 2.1.2 on 2018-10-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='price_L',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price_M',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price_S',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
