# Generated by Django 2.1.2 on 2018-10-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181005_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='coffee.jpg', upload_to='offer-imgs'),
        ),
        migrations.AddField(
            model_name='provider',
            name='image',
            field=models.ImageField(default='provider.jpg', upload_to='provider-imgs'),
        ),
    ]
